import type { LevelConfig } from "./types";

export const LEVELS: Record<number, LevelConfig> = {
  1: {
    name: "Beginner",
    subtitle: "Sees 1 cell away",
    depth: 0,
    timeMs: 0,
    eval: "simple",
    useTT: false,
    candidateRadius: 1,
    scoreScale: 0.3,
  },
  2: {
    name: "Easy",
    subtitle: "Thinks 1 move",
    depth: 2,
    timeMs: 300,
    eval: "simple",
    useTT: false,
    candidateRadius: 2,
    scoreScale: 1,
  },
  3: {
    name: "Medium",
    subtitle: "Pattern matching",
    depth: 4,
    timeMs: 500,
    eval: "patterns",
    useTT: true,
    candidateRadius: 2,
    scoreScale: 1,
  },
  4: {
    name: "Hard",
    subtitle: "Fork detection",
    depth: 6,
    timeMs: 1000,
    eval: "patterns-forks",
    useTT: true,
    candidateRadius: 2,
    scoreScale: 1,
  },
  5: {
    name: "Expert",
    subtitle: "Deep search",
    depth: 8,
    timeMs: 2000,
    eval: "patterns-forks",
    useTT: true,
    candidateRadius: 2,
    scoreScale: 1,
  },
  6: {
    name: "Master",
    subtitle: "Full search",
    depth: 10,
    timeMs: 3000,
    eval: "patterns-forks",
    useTT: true,
    candidateRadius: 2,
    scoreScale: 1,
  },
};
